wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1710759282.912571
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 11
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.14.0
      6: 4.21.3
      8:
      - 5
batch_size:
  desc: null
  value: 32
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 200
generation_steps:
  desc: null
  value: 101
img_size:
  desc: null
  value: 224
iou_loss_weight:
  desc: null
  value: 0.8
l1_lambda:
  desc: null
  value: 1.0e-08
lr:
  desc: null
  value: 1.0e-05
max_len:
  desc: null
  value: 100
model_name:
  desc: null
  value: deit3_medium_patch16_224.fb_in22k_ft_in1k
model_save_path:
  desc: null
  value: /mnt/sdb/2024/pix_2_seq_with_captions_march/output_1/
num_bins:
  desc: null
  value: 224
num_patches:
  desc: null
  value: 196
patience:
  desc: null
  value: 190
weight_decay:
  desc: null
  value: 0.0001
